#!/usr/bin/env bash

module="main"
attr="app"
port="$(cat config.toml | grep ^port | sed "s/^port\s\?=\?\(\w*\)/\1/")"
host="0.0.0.0"

uv run uvicorn "$module:$attr" \
	--reload \
	--host "$host" \
	--port "$port" \
	--reload \
	--reload-dir "localbook" \
	--reload-dir "static" \
	--reload-dir "templates" \
	--reload-include "*.jinja" \
	--reload-include "*.py" \
	--reload-include "*.js" \
	--reload-include "*.mjs" \
	--reload-include "*.css" \
	--log-level "debug"
