name: Tests

on:
  push:
  pull_request:
    
jobs:
  main-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: PYTHONPATH=tests uv run pytest tests -v

